services:
  modechoice:
    build: 
      context: .
      dockerfile: DockerFile
    image: modechoice:latest
    container_name: modechoice
    command: ["python", "-m", "code.main_mc", "${ESTIMATE_MODE}", "${INPUT}", "${OUTPUT}", "${MODEL_NAME}"]
    working_dir: /app
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./code
        target: /app/code
      - type: bind
        source: ./data/input
        target: /app/input
        read_only: true
      - type: bind
        source: ./data/output
        target: /app/output
    tty: true
