# ベースイメージ
FROM python:3

# 作業ディレクトリの作成
WORKDIR /app

# 必要なシステムパッケージのインストール
RUN apt-get update && apt-get install -y tzdata \
    libgdal-dev
RUN pip install GDAL==$(gdal-config --version) --global-option=build_ext --global-option="-I/usr/include/gdal"

# 必要なファイルをコピー（requirements.txtがあれば先にコピー）
COPY requirements.txt ./

# 依存パッケージのインストール
RUN pip install --no-cache-dir -r requirements.txt

